# Generated by Django 5.1.6 on 2025-03-16 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_review_recipe_remove_review_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='myapp.recipe'),
        ),
    ]
